sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - sudo apt install imagemagick
    - sudo apt install ghostscript
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x web_log.tsv.7z

script:
  - bash test.sh
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -h
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -q 900 Linux系统与网络管理/chap0x04/images/car.jpeg dcar.jpeg
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -r 50% Linux系统与网络管理/chap0x04/images/o666.png ro666.png
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -r 256x256 Linux系统与网络管理/chap0x04/images/car.jpeg rcar.jpeg
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -w Linux系统与网络管理/chap0x04/images/car.jpeg thisisfun wcar.jpeg
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -w Linux系统与网络管理/chap0x04/images/o666.png thisisfun wo666.png
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -m Linux系统与网络管理/chap0x04/images/car mmmcar *
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -m Linux系统与网络管理/chap0x04/images/.jpeg .png *
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -c Linux系统与网络管理/chap0x04/images/o666.png co666.jpeg  
  - bash Linux系统与网络管理/chap0x04/script/imgpro.sh -c Linux系统与网络管理/chap0x04/images/gen.svg cgen.jpeg 
  
  - bash Linux系统与网络管理/chap0x04/script/worldinfoproc.sh -h
  - bash Linux系统与网络管理/chap0x04/script/worldinfoproc.sh -rage
  - bash Linux系统与网络管理/chap0x04/script/worldinfoproc.sh -posi
  - bash Linux系统与网络管理/chap0x04/script/worldinfoproc.sh -name
  - bash Linux系统与网络管理/chap0x04/script/worldinfoproc.sh -tage
  
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -h
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -h
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -th 
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -ti
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -tu
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -sp
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -su
  - bash Linux系统与网络管理/chap0x04/script/webtextbach.sh -gu /shuttle/resources/orbiters/discovery.html

after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck Linux系统与网络管理/chap0x04/script/*.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
