sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - sudo apt install imagemagick
    - sudo apt install ghostscript
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x web_log.tsv.7z

script:
  - bash test.sh
  - bash chap0x04/script/imgpro.sh -h
  - bash chap0x04/script/worldinfoproc.sh -h
  - bash chap0x04/script/worldinfoproc.sh -rage
  - bash chap0x04/script/worldinfoproc.sh -posi
  - bash chap0x04/script/worldinfoproc.sh -name
  - bash chap0x04/script/worldinfoproc.sh -tage
  - bash chap0x04/script/webtextbach.sh -h
  - bash chap0x04/script/webtextbach.sh -h
  - bash chap0x04/script/webtextbach.sh -th 
  - bash chap0x04/script/webtextbach.sh -ti
  - bash chap0x04/script/webtextbach.sh -tu
  - bash chap0x04/script/webtextbach.sh -sp
  - bash chap0x04/script/webtextbach.sh -su
  - bash chap0x04/script/webtextbach.sh -gu /shuttle/resources/orbiters/discovery.html

after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck chap0x04/script/*.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
